#!/usr/bin/env python3
"""Validate HD soak reports generated by scripts/smoke/run_hd_soak.ps1."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
PROTECTED_STABLE_STAGE = (
    "gameplay-menu640-centered-map12-dynorigin-mapsurface-scrollclamp-presentbounds-"
    "minimapright-dynvswitch"
)
RUNTIME_POLICY = (
    "repo-only soak report inspection; does not launch Clash95, CDB, wrappers, "
    "PowerShell harnesses, or visible windows"
)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def status_text(passed: bool) -> str:
    return "PASS" if passed else "FAIL"


def check_record(passed: bool, summary: dict[str, Any], failures: list[str] | None = None) -> dict[str, Any]:
    return {"passed": passed, "summary": summary, "failures": failures or []}


def is_under_repo(path_text: str | None) -> bool:
    if not path_text:
        return False
    try:
        path = Path(path_text)
        if not path.is_absolute():
            path = REPO_ROOT / path
        path.resolve().relative_to(REPO_ROOT.resolve())
        return True
    except ValueError:
        return False


def numbers(values: list[Any]) -> list[float]:
    result: list[float] = []
    for value in values:
        if value is None:
            continue
        result.append(float(value))
    return result


def evaluate_report(
    report: dict[str, Any],
    *,
    min_frames: int = 2,
    min_nonblack_percent: float = 10.0,
    min_unique_sample_colors: int = 8,
    max_artifact_mb: int = 250,
    expected_width: int = 800,
    expected_height: int = 600,
) -> dict[str, Any]:
    frame_samples = list(report.get("frame_samples") or [])
    route_results = list(report.get("route_results") or [])
    artifact_bytes = int(report.get("artifact_bytes") or 0)
    artifact_limit_bytes = int(max_artifact_mb) * 1024 * 1024

    checks: dict[str, Any] = {}

    failures: list[str] = []
    executed = report.get("executed") is True
    if not executed:
        failures.append("soak report was not produced by an execution run")
    checks["executed"] = check_record(executed, {"executed": report.get("executed")}, failures)

    failures = []
    stage_ok = report.get("stage") == PROTECTED_STABLE_STAGE
    stable_unchanged = report.get("stable_stage_should_change") is False
    if not stage_ok:
        failures.append(f"stage is {report.get('stage')}, expected protected stable stage")
    if not stable_unchanged:
        failures.append("report would change the stable stage")
    checks["protected_stage"] = check_record(
        stage_ok and stable_unchanged,
        {
            "stage": report.get("stage"),
            "stable_stage_should_change": report.get("stable_stage_should_change"),
        },
        failures,
    )

    failures = []
    policy = str(report.get("runtime_policy") or "")
    input_class = str(report.get("input_proof_class") or "")
    opt_in = "opt-in" in policy.lower()
    not_manual_release = "not_manual" in input_class.lower() or "diagnostic" in input_class.lower()
    rb_blocked = report.get("right_bottom_promotion_blocked") is True
    if not opt_in:
        failures.append("runtime policy does not record opt-in execution")
    if not not_manual_release:
        failures.append("input proof class does not mark the run as diagnostic")
    if not rb_blocked:
        failures.append("right-bottom promotion is not recorded as blocked")
    checks["promotion_boundary"] = check_record(
        opt_in and not_manual_release and rb_blocked,
        {
            "runtime_policy": policy,
            "input_proof_class": input_class,
            "right_bottom_promotion_blocked": report.get("right_bottom_promotion_blocked"),
        },
        failures,
    )

    failures = []
    candidate_outside_repo = not is_under_repo(report.get("candidate"))
    output_outside_repo = not is_under_repo(report.get("output_directory"))
    if not candidate_outside_repo:
        failures.append("candidate path is inside the repository")
    if not output_outside_repo:
        failures.append("raw output directory is inside the repository")
    checks["artifact_locations"] = check_record(
        candidate_outside_repo and output_outside_repo,
        {"candidate": report.get("candidate"), "output_directory": report.get("output_directory")},
        failures,
    )

    failures = []
    frame_count = int(report.get("frame_sample_count") or len(frame_samples))
    if frame_count < min_frames:
        failures.append(f"frame sample count {frame_count} is below {min_frames}")
    size_bad = [
        frame
        for frame in frame_samples
        if int(frame.get("Width") or 0) != expected_width or int(frame.get("Height") or 0) != expected_height
    ]
    if size_bad:
        failures.append(f"{len(size_bad)} frame samples were not {expected_width}x{expected_height}")
    checks["frame_inventory"] = check_record(
        frame_count >= min_frames and not size_bad,
        {"frame_sample_count": frame_count, "expected_size": [expected_width, expected_height]},
        failures,
    )

    failures = []
    nonblack_values = numbers([frame.get("NonblackPercent") for frame in frame_samples])
    unique_values = numbers([frame.get("UniqueSampleColors") for frame in frame_samples])
    min_nonblack = min(nonblack_values) if nonblack_values else 0.0
    min_unique = min(unique_values) if unique_values else 0.0
    if min_nonblack < min_nonblack_percent:
        failures.append(f"minimum nonblack percent {min_nonblack} is below {min_nonblack_percent}")
    if min_unique < min_unique_sample_colors:
        failures.append(f"minimum unique sampled colors {min_unique} is below {min_unique_sample_colors}")
    checks["render_metrics"] = check_record(
        min_nonblack >= min_nonblack_percent and min_unique >= min_unique_sample_colors,
        {"min_nonblack_percent": min_nonblack, "min_unique_sample_colors": min_unique},
        failures,
    )

    failures = []
    unexpected_exit = report.get("process_exited_unexpectedly") is True
    clean_stop = report.get("clean_stop") is True
    if unexpected_exit:
        failures.append(f"process exited unexpectedly with code {report.get('exit_code')}")
    if not clean_stop:
        failures.append("process was not stopped cleanly by the harness")
    checks["process_liveness"] = check_record(
        not unexpected_exit and clean_stop,
        {"process_exited_unexpectedly": unexpected_exit, "exit_code": report.get("exit_code"), "clean_stop": clean_stop},
        failures,
    )

    failures = []
    route_failures = [
        row
        for row in route_results
        if row.get("PathVerified") is False or (row.get("Click") is True and row.get("ClickPathVerified") is False)
    ]
    if route_failures:
        failures.append(f"{len(route_failures)} route/input rows did not verify")
    checks["input_responsiveness"] = check_record(
        not route_failures,
        {"route_result_count": len(route_results), "route_failure_count": len(route_failures)},
        failures,
    )

    failures = []
    if artifact_bytes > artifact_limit_bytes:
        failures.append(f"artifact bytes {artifact_bytes} exceeds limit {artifact_limit_bytes}")
    checks["artifact_budget"] = check_record(
        artifact_bytes <= artifact_limit_bytes,
        {"artifact_bytes": artifact_bytes, "artifact_limit_bytes": artifact_limit_bytes},
        failures,
    )

    all_failures = [failure for check in checks.values() for failure in check["failures"]]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "runtime_policy": RUNTIME_POLICY,
        "overall": not all_failures,
        "source_report": report.get("report_json"),
        "stage": report.get("stage"),
        "tier": report.get("tier"),
        "route": report.get("route"),
        "duration_sec": report.get("duration_sec"),
        "checks": checks,
        "failures": all_failures,
    }


def to_markdown(evaluation: dict[str, Any]) -> str:
    lines = [
        "# HD Soak Report Guard",
        "",
        f"- Overall: {status_text(bool(evaluation['overall']))}",
        f"- Generated: `{evaluation['generated_at']}`",
        f"- Runtime policy: `{evaluation['runtime_policy']}`",
        f"- Stage: `{evaluation.get('stage')}`",
        f"- Tier / route: `{evaluation.get('tier')}` / `{evaluation.get('route')}`",
        f"- Duration seconds: `{evaluation.get('duration_sec')}`",
        "",
        "## Checks",
        "",
    ]
    for name, check in evaluation["checks"].items():
        lines.append(f"- `{name}`: `{status_text(bool(check['passed']))}`")
    if evaluation["failures"]:
        lines.extend(["", "## Failures", ""])
        for failure in evaluation["failures"]:
            lines.append(f"- {failure}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path)
    parser.add_argument("--write-json", type=Path)
    parser.add_argument("--write-markdown", "--write-md", dest="write_markdown", type=Path)
    parser.add_argument("--require-pass", action="store_true")
    args = parser.parse_args()

    evaluation = evaluate_report(load_json(args.report))
    if args.write_json:
        args.write_json.parent.mkdir(parents=True, exist_ok=True)
        args.write_json.write_text(json.dumps(evaluation, indent=2), encoding="ascii")
    if args.write_markdown:
        args.write_markdown.parent.mkdir(parents=True, exist_ok=True)
        args.write_markdown.write_text(to_markdown(evaluation), encoding="ascii")

    print(f"overall: {status_text(bool(evaluation['overall']))}")
    print(f"runtime-policy: {evaluation['runtime_policy']}")
    print(f"stage: {evaluation.get('stage')}")
    print(f"tier-route: {evaluation.get('tier')} / {evaluation.get('route')}")
    if evaluation["failures"]:
        print("failures:")
        for failure in evaluation["failures"]:
            print(f"  - {failure}")
    if args.require_pass and not evaluation["overall"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
